#!/usr/bin/env bash
#hour clock script 
minute=1
hour=0
while [ $hour -lt 12 ]
do
echo "hour: $hour"
minute=1
while [ $minute -lt 60 ]
do
echo "$minute"
((minute++))
sleep 0.5
done
((hour++))
sleep 1
done
